services:
  mysql:
    image: mysql:8.0
    container_name: death_stranding_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: death_stranding
    ports:
      - "3306:3306"
    volumes:
      - ./inicializar:/docker-entrypoint-initdb.d